-- Схема памяти aida для нового проекта Supabase (Postgres + pgvector).
-- Запуск: psql "$SUPABASE_DB_URL" -f setup.sql   (или вставить в SQL Editor).
-- Очереди pending_* живут в локальном SQLite на машине агента, в базе их нет.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS memories (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_type   text        NOT NULL DEFAULT 'fact',
    content       text        NOT NULL CHECK (char_length(content) BETWEEN 1 AND 2000),
    priority      text        NOT NULL DEFAULT 'P2',
    status        text        NOT NULL DEFAULT 'active',
    chat_id       text,
    embedding     vector(2048),
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', content))  STORED,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_accessed timestamptz,
    access_count  integer     NOT NULL DEFAULT 0,
    role          text,
    search_ru     tsvector GENERATED ALWAYS AS (to_tsvector('russian', content)) STORED
);

CREATE INDEX IF NOT EXISTS memories_search_idx      ON memories USING gin (search_vector);
CREATE INDEX IF NOT EXISTS memories_search_ru_idx   ON memories USING gin (search_ru);
CREATE INDEX IF NOT EXISTS memories_chat_idx        ON memories (chat_id);
CREATE INDEX IF NOT EXISTS memories_chat_role_idx   ON memories (chat_id, role);
CREATE INDEX IF NOT EXISTS memories_priority_idx    ON memories (priority);
CREATE INDEX IF NOT EXISTS memories_status_idx      ON memories (status);

-- Доступ только по прямому подключению владельца; публичный API Supabase закрыт.
ALTER TABLE memories ENABLE ROW LEVEL SECURITY;
